from django.db import models

# Create your models here.
class FoodDetails(models.Model):
    name=models.CharField(max_length=200)
    area=models.CharField(max_length=200)
    writer=models.CharField(max_length=200)
    category=models.CharField(max_length=200)
    quotes=models.JSONField(null=False)
    step1 = models.CharField(max_length=500, null=True,blank=True)
    step2 = models.CharField(max_length=500, null=True,blank=True)
    step3 = models.CharField(max_length=500, null=True,blank=True)
    step4 = models.CharField(max_length=500, null=True,blank=True)
    step5 = models.CharField(max_length=500, null=True,blank=True)
    step6 = models.CharField(max_length=500, null=True,blank=True)
    step7 = models.CharField(max_length=500, null=True,blank=True)
    step8 = models.CharField(max_length=500, null=True,blank=True)
    step9 = models.CharField(max_length=500, null=True,blank=True)
    step10 = models.CharField(max_length=500, null=True,blank=True)
    ing1 = models.CharField(max_length=500, null=True,blank=True)
    ing2 = models.CharField(max_length=500, null=True,blank=True)
    ing3 = models.CharField(max_length=500, null=True,blank=True)
    ing4 = models.CharField(max_length=500, null=True,blank=True)
    ing5 = models.CharField(max_length=500, null=True,blank=True)
    ing6 = models.CharField(max_length=500, null=True,blank=True)
    ing7 = models.CharField(max_length=500, null=True,blank=True)
    ing8 = models.CharField(max_length=500, null=True,blank=True)
    ing9 = models.CharField(max_length=500, null=True,blank=True)
    ing10 = models.CharField(max_length=500, null=True,blank=True)
    ing11 = models.CharField(max_length=500, null=True,blank=True)
    ing12 = models.CharField(max_length=500, null=True,blank=True)
    ing13 = models.CharField(max_length=500, null=True,blank=True)
    ing14 = models.CharField(max_length=500, null=True,blank=True)
    ing15 = models.CharField(max_length=500, null=True,blank=True)
    pic1 = models.ImageField(upload_to='food_images/', null=False)
    pic2 = models.ImageField(upload_to='food_images/', null=False)